# Site settings
name: Matt Gauger
title: Matt Gauger
email: contact@mattgauger.com
description: > # this means to ignore newlines until "baseurl:"

paginate: 10
paginate_path: '/posts/:num'
url: "https://blog.mattgauger.com" # the base hostname & protocol for your site
baseurl: ""
github_username: mathias

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
source: "source"
deploy: "_deploy"
destination: "_deploy"
permalink: "pretty"

# Plugins, extensions, etc:
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
redirect_from:
  json: false
exclude:
  - README.md
  - LICENSE.md
